import { Link } from "react-router-dom";
import { Panel } from "../components/ui";

const steps = [
  ["Using your official school returns", "In Imports, upload OVER ALL first. The app reads all staff sheets and creates schools where block details are available. Check rows needing attention, then Save changes. Next upload the 13A PDF, check every centre's host school, linked schools and student numbers, and save. Scanned PDFs are read on this device but may contain reading mistakes: correct unclear numbers instead of guessing. The standard and year must match the examination. For practical exams, enter the actual students per subject in Practical subject counts; these cannot be worked out from centre totals.", "/imports", "Import official returns"],
  ["Custodian duties", "In Theory, add the centres used as custodian points and tick the schools each serves. The initial count is one custodian per ten schools. You may change the count, but give a reason and save. Only PG and BT Assistants are eligible. The app checks previous duty, distance, exemptions and overlapping sessions. It reports unfilled posts. No points saved means no custodian duties will be generated.", "/theory", "Set up custodians"],
  ["Incoming and outgoing school lists", "In Reports, School-wise duty lists combines the latest theory, hall and practical results for this examination. Duty-In lists teachers at the school receiving them. Duty-Out lists teachers under their current school and shows where they are going. Download Word for printing or Excel for checking. Practical letters include batches and internal/external examiners, using the real allotted dates.", "/reports", "Download school-wise lists"],
  ["1. Add schools and teachers", "Add blocks first, then schools, then teachers. A school's centre code is optional: enter it for an exam centre and leave it blank for other schools. The app creates the centre automatically. Teachers do not need employee codes. To edit someone, choose their name from the list. Find their location using offline maps or enter latitude and longitude.", "/master", "Open Schools & teachers"],
  ["Importing Excel files", "Open Imports and choose an .xlsx file. Put headings such as Teacher, Teacher Post, School, Centre Code and Block in the first row; columns can be in any order. Check each Save as choice and select a field for unfamiliar headings, or leave that column out. The Upload teacher workbook button also reads the official HM, PG, BT, BT NON, SGT, SPL and NON TEACHING sheets together. It keeps office staff separate. Add schools, blocks and coordinates first, then check the Teacher review and select Save changes. Blank cells keep saved details unchanged. Teachers absent from the file are kept by default. If two teachers at the same school have the same name, add or edit them separately in Schools & teachers.", "/imports", "Open Imports"],
  ["2. Add the exam timetable", "Open Exam cycle. Enter the exam dates, then use Download timetable template to fill in Date, Session, School name and Subject / paper. Upload the file, check the preview and choose Use uploaded timetable before saving. The school name must be from your saved school list; leave it blank or write All schools when a session applies everywhere.", "/cycles", "Open Exam cycle"],
  ["3. Create duty lists", "Generate Theory, Practical and Hall duty lists. A marked theory centre session plans one Chief, one Departmental Officer (two above 500 students) and two office staff. Read any shortage message; the system never hides a shortage by assigning an unsuitable person.", "/theory", "Create Theory list"],
  ["4. Check before approval", "Open Check list to see conflicts, missing information and warnings. Correct the source data or record an authorised exception before approval.", "/validation", "Open Check list"],
  ["5. Print and share", "Open Reports to download school-wise, teacher-wise and duty reports. The layouts use the Directorate heading and table style from the 2026 Chief/Department, Custodian, Liaison and Route Officer lists.", "/reports", "Open Reports"],
  ["Activity log", "This is a record of changes: what was added or edited, when it happened and any reason given. Use it to check previous imports, manual teacher replacements and downloaded reports. You do not need to enter anything here.", "/audit", "Open Activity log"],
  ["Backups", "Save a backup before making large changes. It is a separate copy you can use if the computer fails or information is changed by mistake. Restoring a backup replaces current data, so check it carefully first and keep the backup password safe.", "/backups", "Open Backups"],
  ["Settings", "Check whether saved data is available and which allotment rules are in use. Existing examinations keep their own rules so earlier duty lists remain consistent.", "/settings", "Open Settings"],
];

export function HelpPage() {
  return <Panel title="How to use this app">
    <p className="mb-5 text-sm text-[var(--color-ink-muted)]">Use this guide in order for each examination. Your work is saved automatically on this computer.</p>
    <ol className="space-y-3">{steps.map(([title, text, to, label]) => <li key={title} className="rounded-xl border border-[var(--color-line)] bg-white p-4"><h2 className="font-display text-lg">{title}</h2><p className="mt-1 text-sm text-[var(--color-ink-muted)]">{text}</p><Link className="mt-3 inline-block rounded bg-[var(--color-brand)] px-3 py-2 text-sm text-white" to={to}>{label}</Link></li>)}</ol>
    <div className="mt-5 rounded-xl bg-[var(--color-sky-wash)] p-4 text-sm"><b>Important:</b> Review the printed list before issuing it. If information is wrong, correct Schools & teachers and create a new list; earlier approved lists remain available for reference.</div>
  </Panel>;
}
